= Matt Friedman
Matt Friedman <matt.friedman@gmail.com>
v1.1, Resume Updated for January 2017
:title: Matt Friedman's Resume
:doctype: article
:icons: font
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: Letter

icon:check[] *_Profile_*

Matt Friedman is a technology leader seeking a collaborative role in a modern technology driven environment.

** Provides technical guidance and training while designing and developing strategic business software
** Creates efficient, maintainable and extensible software that meets or exceeds business goals
** 17+ years experience with a proven record of bringing successful projects into production
** Expert in TDD and Continuous Integration
** Teaching and Mentoring
** A lifetime learner of new techniques, APIs and approaches
** Skilled at envisioning and implementing complex enterprise applications
** Strong communication and interpersonal skills


icon:check[] *_Skills_*

[format="dsv"]
|===
Linux  (CentOS/Redhat, Ubuntu) : Java, Groovy, Bash : IntelliJ IDEA, Vim
Gradle, Maven : Spring Cloud/Boot/MVC/Integration and all things Spring \:)  : Elastic, RabbitMQ, Ehcache Kafka
Javascript, Knockout, AngularJS : JUnit, Spock, Mockito  : JMeter, Robot, Cucumber
Kubernetes, Mesos, Marathon, DC/OS : JAXB, Jackson, JSON, XML : Postgresql, MySQL
git, svn, cvs : Jenkins, Bamboo, CI/CD : Tomcat, Jetty, Glassfish
nginx, httpd :  The Netflix Stack (Ribbon, Feign, Eureka etc...)  : Docker, Vagrant, VirtualBox
|===


<<<


icon:industry[] *_Professional Experience_*

*Exchange Solutions Inc.*

_December 2015 - Present; Toronto, Ontario_

_Software Architect_

Technology Leader reporting to the Team Lead and working directly with the VP of Technology and CTO.

** Provided technical advice and guidance to the CTO (topics such as TDD, Automation, CI/CD, Agile...)
** Seen as a mentor for intermediate and junior developers
** Composed the team's Coding Practices and Definition of Done
** Composed and presented a Continuous Delivery strategy including a complete Delivery Pipeline using Gradle and Jenkins
** Implemented RESTful clients and services key to the business (Spring RestTemplate / Netflix Feign)
** Created Kubernetes-ready clustered rabbitmq image and configuration (declarative)
** Instrumental in the expansion of TDD, Automation and Agile methodologies at ESI

*Afilias Inc. - Global Registry Services*

_October 2011 - November 2015_

_Senior Developer / Architect_

Designed and developed Spring applications for Afilias Global Registry Services.

** Confidently released tested APIs and services into production with no issues
** Design and implement RESTful APIs
** Design and implement improvements to key B2B server software (NIO/Netty)
** Provide architectural and technical implementation guidance
** Company Leader in TDD and Continuous Integration




**Contract Architect &amp; Developer**

_April 2009 - November 2011_

_Contract Architect &amp; Developer_

Various contracts for Pro Active Water Solutions, Financial Wellness Planning, TheParentReport.com.


<<<



**Symcor Inc.**

_January 2007 - April 2009_

_Software Architect_

** Team lead / architect of redesign and reimplementation of ePresentment, Symcor's
multi-terabyte document storage and retrieval system
** Performed post-implementation optimization of ePresentment resulting in a 10 fold
increase in performance and speed of document processing and significant cost savings (jprobe profiler)







**Symcor Inc.**

_January 2006 - January 2007_

_Developer V / Architect_

** Led the Communicator development team to successful completion of the Communicator Product which was
designed to be fully modularized and customizable, leading to faster implementation times and
elimination of the need to alter code per client implementation


**Symcor Inc.**

_January 2005 - January 2006_

_Developer IV_

** Developed and presented to senior management a project plan to re-implement Communicator as a customizable product
** Managed client customizations of Communicator
** Worked with the team to continuously improve and refactor the structure of the Communicator code base





**Symcor Inc.**

_January 2003 - February 2005_

_Developer III_

** Redesigned and re-implemented the specialized JavaScript text editor in Communicator resulting in customization of the tool
without altering the code (templates)
** Managed per client customizations of Communicator


<<<





**CTV &amp; Bell Globe Media Interactive**

_March 2001 - October 2002_

_Client / Server Programmer_

** Key developer on BGMi's "Entry Point" content management system, used to manage a number of sites such as the
company's corporate communications site, www.bellglobemedia.ca, and www.theComedyNetwork.ca



**Spry New Media**

_March 2000 - February 2001_

_Principal and Lead Programmer_

** Lead Developer and database designer for: www.theparentreport.com
** Gathered requirements from the client



**Computer Master Technical Centre**

_December 1999 - February 2000_

_Contract Programmer_

** Hired as a contract programmer immediately upon graduation
** Designed and implemented a searchable skills database application where students could maintain their online
portfolios; employers could search for students with specific skill sets




**100.3 The Q Radio, Victoria, B.C.**

_December 1996 - December 1999_

_Audio Engineer_

** Audio production for commercials, promotions. Talent direction and client assistance.




**Q92 / 790 CIGM Radio, Sudbury, Ontario**

_December 1994 - December 1996_

_Audio Production Manager_

** Responsible for coordinating audio production for promotions and advertisements, directing talent,
managing production staff, working with writers and assisting clients.



<<<





icon:certificate[] *_Training &amp; Education_*

* Elastic Search Training - Toronto, ON - 2015
* Spring Core Training - Toronto, ON - 2014
* Spring Integration Training - Toronto, ON - 2014
* Zend PHP Certified Engineer - Toronto, ON - 2005

**Computer Master Technology Centre**

_1999 - 1999 (3 months)_

_Web Applications Diploma_

** Web Application Development in HTML, Java and PHP



**Fanshawe College**

_1992 - 1994_

_Radio Broadcasting Diploma_

** Broadcasting diploma


**Wilfrid Laurier University**

_1989 - 1991_

_Honours Business Administration_



icon:flask[] *_Hobbies and Interests_*

** Film &amp; Digital Photography <https://500px.com/mattfriedman>
** 4x4 adventures
** Hiking &amp; Wilderness Camping
** The craft of software design &amp; implementation






















